### ISSUE TITLE
broker implementation in C not purging expired workers

### ISSUE THREAD

**Issue by JoergSchneiderSimon** [desmoteo/IronDomo#1]
s_broker_purge() is assuming workers in the self->_waiting list are sorted by oldest first.

the original libmdp achieved that by pushing a worker element to the end of the list upon a heartbeat received.
that part is missing in your implementation. 

As a result expired workers are never purged from the _waiting list.

To fix:
idbrokerapi.h:259ff should read:

 ```
} else if (zframe_streq(command, IDPW_HEARTBEAT)) {
        if (worker_ready) {
            if (zlist_size(self->_waiting) > 1) {
                // Move worker to the end of the waiting queue,
                // so s_broker_purge will only check old worker(s)
                zlist_remove(self->_waiting, worker);
                zlist_append(self->_waiting, worker);
            }
            worker->_expiry = zclock_time() + HEARTBEAT_EXPIRY;
```

cheers, 

Joerg

**Comment by desmoteo** [comment]
Hi @JoergSchneiderSimon  

Sorry for the late reply. You are right, thanks for the fix. Should be available as of commit 

https://github.com/desmoteo/IronDomo/commit/c1446103e93a1a1bae846f3ba9ed0415f00df293

Let me know

Matteo
